# Generated by Django 3.1.2 on 2020-10-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('profile_photo', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'name',
                'ordering': ['uid'],
            },
        ),
    ]
