# Generated by Django 3.1.2 on 2020-10-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201030_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='cast',
            new_name='cast_id',
        ),
        migrations.RenameField(
            model_name='cast',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='director_id',
        ),
        migrations.RenameField(
            model_name='movie_genre',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.AlterUniqueTogether(
            name='cast',
            unique_together={('cast_id', 'movie_id')},
        ),
        migrations.AlterUniqueTogether(
            name='movie_genre',
            unique_together={('movie_id', 'genre_type')},
        ),
    ]
