# Generated by Django 3.1.2 on 2020-10-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20201030_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='cast_id',
            new_name='cast',
        ),
        migrations.RenameField(
            model_name='cast',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director_id',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movie_genre',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.AlterUniqueTogether(
            name='cast',
            unique_together={('cast', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='movie_genre',
            unique_together={('movie', 'genre_type')},
        ),
    ]
