# Generated by Django 3.1.2 on 2020-11-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20201102_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='../movies/posters'),
        ),
    ]
