# Generated by Django 3.1.2 on 2020-11-04 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20201104_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
        migrations.DeleteModel(
            name='MoviePosters',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserBannedList',
        ),
        migrations.DeleteModel(
            name='WatchHistory',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
        migrations.AlterModelOptions(
            name='cast',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AddField(
            model_name='movie_genre',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='movie_genre',
            unique_together={('movie', 'genre_type')},
        ),
    ]
