# Generated by Django 3.1.2 on 2020-11-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_wish_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='movie',
            name='votecount',
            field=models.IntegerField(default=0),
        ),
    ]
