# Generated by Django 3.1.2 on 2020-11-08 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20201108_0334'),
        ('movies', '0022_auto_20201107_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='login.user'),
        ),
    ]
