# Generated by Django 3.1.2 on 2020-11-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_auto_20201109_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('bag_of_words', models.TextField(max_length=1000)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
