# Generated by Django 3.1.2 on 2020-11-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='moviegenre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='movieposters',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userbannedlist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'managed': True},
        ),
    ]
